import type { Entity, PropertyMapping, PlatformRule } from '@/types';

export const mockEntities: Entity[] = [
  {
    id: '1',
    type: 'product',
    name: '产品',
    properties: [
      { id: 'p1', name: 'name', type: 'string', required: true, description: '产品名称' },
      { id: 'p2', name: 'sku', type: 'string', required: true, description: '产品SKU' },
      { id: 'p3', name: 'description', type: 'string', required: false, description: '产品描述' },
      { id: 'p101', name: 'category', type: 'string', required: false, description: '产品分类' },
      { id: 'p102', name: 'brand', type: 'string', required: false, description: '品牌' },
      { id: 'p103', name: 'model', type: 'string', required: false, description: '型号' },
      { id: 'p104', name: 'weight', type: 'number', required: false, description: '重量(kg)' },
      { id: 'p105', name: 'dimensions', type: 'string', required: false, description: '尺寸' },
      { id: 'p106', name: 'color', type: 'string', required: false, description: '颜色' },
      { id: 'p107', name: 'material', type: 'string', required: false, description: '材质' },
      { id: 'p108', name: 'countryOfOrigin', type: 'string', required: false, description: '原产国' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    type: 'instance',
    name: '实例',
    properties: [
      { id: 'p4', name: 'name', type: 'string', required: true, description: '实例名称' },
      { id: 'p5', name: 'price', type: 'number', required: true, description: '售价' },
      { id: 'p6', name: 'title', type: 'string', required: true, description: '商品标题' },
      { id: 'p7', name: 'images', type: 'array', required: false, description: '商品图片' },
      { id: 'p8', name: 'description', type: 'string', required: false, description: '描述词' },
      { id: 'p109', name: 'bulletPoints', type: 'array', required: false, description: '要点/卖点' },
      { id: 'p110', name: 'keywords', type: 'array', required: false, description: '关键词' },
      { id: 'p111', name: 'searchTerms', type: 'string', required: false, description: '搜索词' },
      { id: 'p112', name: 'variations', type: 'array', required: false, description: '变体信息' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    type: 'instance',
    name: 'Amazon实例',
    parentId: '2',
    properties: [
      { id: 'p201', name: 'amazonProductId', type: 'string', required: false, description: 'Amazon Product ID' },
      { id: 'p202', name: 'parentAsin', type: 'string', required: false, description: 'Parent ASIN' },
      { id: 'p203', name: 'variationTheme', type: 'string', required: false, description: '变体主题' },
      { id: 'p204', name: 'brandStore', type: 'string', required: false, description: '品牌旗舰店' },
      { id: 'p205', name: 'aPlusContent', type: 'string', required: false, description: 'A+内容' },
      { id: 'p206', name: 'backendKeywords', type: 'string', required: false, description: '后端关键词' },
      { id: 'p207', name: 'manufacturer', type: 'string', required: false, description: '制造商' },
      { id: 'p208', name: 'itemPackageQuantity', type: 'number', required: false, description: '包装数量' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    type: 'instance',
    name: 'Target实例',
    parentId: '2',
    properties: [
      { id: 'p301', name: 'targetDPCI', type: 'string', required: false, description: 'DPCI编号' },
      { id: 'p302', name: 'targetTCIN', type: 'string', required: false, description: 'TCIN编号' },
      { id: 'p303', name: 'department', type: 'string', required: false, description: '部门' },
      { id: 'p304', name: 'storePickup', type: 'boolean', required: false, description: '到店取货' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    type: 'instance',
    name: 'TikTok实例',
    parentId: '2',
    properties: [
      { id: 'p401', name: 'tiktokProductId', type: 'string', required: false, description: 'TikTok产品ID' },
      { id: 'p402', name: 'videoUrl', type: 'string', required: false, description: '视频链接' },
      { id: 'p403', name: 'hashtags', type: 'array', required: false, description: '话题标签' },
      { id: 'p404', name: 'influencerCollab', type: 'boolean', required: false, description: '达人合作' },
      { id: 'p405', name: 'liveStream', type: 'boolean', required: false, description: '直播带货' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    type: 'instance',
    name: 'Best Buy实例',
    parentId: '2',
    properties: [
      { id: 'p501', name: 'sku', type: 'string', required: false, description: 'SKU' },
      { id: 'p502', name: 'upc', type: 'string', required: false, description: 'UPC' },
      { id: 'p503', name: 'categoryPath', type: 'string', required: false, description: '分类路径' },
      { id: 'p504', name: 'warranty', type: 'string', required: false, description: '保修信息' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    type: 'instance',
    name: 'Allegro实例',
    parentId: '2',
    properties: [
      { id: 'p601', name: 'allegroId', type: 'string', required: false, description: 'Allegro ID' },
      { id: 'p602', name: 'parameterGroup', type: 'string', required: false, description: '参数组' },
      { id: 'p603', name: 'europeanArticleNumber', type: 'string', required: false, description: 'EAN' },
      { id: 'p604', name: 'vatRate', type: 'string', required: false, description: '增值税税率' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    type: 'instance',
    name: 'Kohls实例',
    parentId: '2',
    properties: [
      { id: 'p701', name: 'kohlsStyleNumber', type: 'string', required: false, description: 'Kohls款号' },
      { id: 'p702', name: 'department', type: 'string', required: false, description: '部门' },
      { id: 'p703', name: 'sizeChart', type: 'string', required: false, description: '尺码表' },
      { id: 'p704', name: 'kohlsCash', type: 'boolean', required: false, description: 'Kohls现金' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    type: 'instance',
    name: 'Wayfair实例',
    parentId: '2',
    properties: [
      { id: 'p801', name: 'wayfairSKU', type: 'string', required: false, description: 'Wayfair SKU' },
      { id: 'p802', name: 'assemblyRequired', type: 'boolean', required: false, description: '需要组装' },
      { id: 'p803', name: 'roomType', type: 'string', required: false, description: '房间类型' },
      { id: 'p804', name: 'shipWeight', type: 'number', required: false, description: '运输重量' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    type: 'instance',
    name: 'eBay实例',
    parentId: '2',
    properties: [
      { id: 'p901', name: 'itemId', type: 'string', required: false, description: 'eBay物品ID' },
      { id: 'p902', name: 'condition', type: 'string', required: false, description: '成色' },
      { id: 'p903', name: 'auctionType', type: 'string', required: false, description: '拍卖类型' },
      { id: 'p904', name: 'bestOffer', type: 'boolean', required: false, description: '议价' },
      { id: 'p905', name: 'handlingTime', type: 'number', required: false, description: '处理时间' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    type: 'instance',
    name: 'Macys实例',
    parentId: '2',
    properties: [
      { id: 'p1001', name: 'macysStyleId', type: 'string', required: false, description: 'Macys款号' },
      { id: 'p1002', name: 'classifications', type: 'string', required: false, description: '分类' },
      { id: 'p1003', name: 'vendorStyle', type: 'string', required: false, description: '供应商款号' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '12',
    type: 'instance',
    name: 'Lowes实例',
    parentId: '2',
    properties: [
      { id: 'p1101', name: 'lowesModelNumber', type: 'string', required: false, description: 'Lowes型号' },
      { id: 'p1102', name: 'storeAvailability', type: 'string', required: false, description: '门店库存' },
      { id: 'p1103', name: 'installation', type: 'boolean', required: false, description: '安装服务' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '13',
    type: 'instance',
    name: 'Walmart实例',
    parentId: '2',
    properties: [
      { id: 'p1201', name: 'walmartItemId', type: 'string', required: false, description: 'Walmart物品ID' },
      { id: 'p1202', name: 'gtin', type: 'string', required: false, description: 'GTIN' },
      { id: 'p1203', name: 'categoryPath', type: 'string', required: false, description: '分类路径' },
      { id: 'p1204', name: 'wfsEligible', type: 'boolean', required: false, description: 'WFS配送' },
      { id: 'p1205', name: 'fulfillmentType', type: 'string', required: false, description: '履约方式' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '14',
    type: 'instance',
    name: 'Temu实例',
    parentId: '2',
    properties: [
      { id: 'p1301', name: 'temuProductId', type: 'string', required: false, description: 'Temu产品ID' },
      { id: 'p1302', name: 'categoryId', type: 'string', required: false, description: '分类ID' },
      { id: 'p1303', name: 'shippingFrom', type: 'string', required: false, description: '发货地' },
      { id: 'p1304', name: 'deliveryDays', type: 'number', required: false, description: '配送天数' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '15',
    type: 'instance',
    name: 'Shopify实例',
    parentId: '2',
    properties: [
      { id: 'p1401', name: 'productId', type: 'string', required: false, description: 'Shopify产品ID' },
      { id: 'p1402', name: 'handle', type: 'string', required: false, description: 'Handle' },
      { id: 'p1403', name: 'collections', type: 'array', required: false, description: '集合' },
      { id: 'p1404', name: 'tags', type: 'array', required: false, description: '标签' },
      { id: 'p1405', name: 'vendor', type: 'string', required: false, description: '供应商' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '16',
    type: 'instance',
    name: 'Shein实例',
    parentId: '2',
    properties: [
      { id: 'p1501', name: 'sheinGoodsNo', type: 'string', required: false, description: 'Shein商品编号' },
      { id: 'p1502', name: 'style', type: 'string', required: false, description: '风格' },
      { id: 'p1503', name: 'season', type: 'string', required: false, description: '季节' },
      { id: 'p1504', name: 'ageGroup', type: 'string', required: false, description: '年龄组' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '17',
    type: 'instance',
    name: 'Overstock实例',
    parentId: '2',
    properties: [
      { id: 'p1601', name: 'overstockSKU', type: 'string', required: false, description: 'Overstock SKU' },
      { id: 'p1602', name: 'condition', type: 'string', required: false, description: '成色' },
      { id: 'p1603', name: 'room', type: 'string', required: false, description: '房间' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '18',
    type: 'instance',
    name: 'Mercado Libre实例',
    parentId: '2',
    properties: [
      { id: 'p1701', name: 'mlItemId', type: 'string', required: false, description: 'ML物品ID' },
      { id: 'p1702', name: 'officialStore', type: 'boolean', required: false, description: '官方店' },
      { id: 'p1703', name: 'freeShipping', type: 'boolean', required: false, description: '包邮' },
      { id: 'p1704', name: 'mercadopago', type: 'boolean', required: false, description: 'Mercado Pago' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '19',
    type: 'instance',
    name: 'About You实例',
    parentId: '2',
    properties: [
      { id: 'p1801', name: 'aboutYouProductId', type: 'string', required: false, description: 'About You产品ID' },
      { id: 'p1802', name: 'season', type: 'string', required: false, description: '季节' },
      { id: 'p1803', name: 'gender', type: 'string', required: false, description: '性别' },
      { id: 'p1804', name: 'sustainability', type: 'string', required: false, description: '可持续性' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '20',
    type: 'instance',
    name: 'Trendyol实例',
    parentId: '2',
    properties: [
      { id: 'p1901', name: 'trendyolProductId', type: 'string', required: false, description: 'Trendyol产品ID' },
      { id: 'p1902', name: 'brandId', type: 'string', required: false, description: '品牌ID' },
      { id: 'p1903', name: 'gender', type: 'string', required: false, description: '性别' },
      { id: 'p1904', name: 'colorGroup', type: 'string', required: false, description: '颜色组' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '21',
    type: 'productItem',
    name: '商品',
    properties: [
      { id: 'p10', name: 'name', type: 'string', required: true, description: '商品名称' },
      { id: 'p11', name: 'price', type: 'number', required: true, description: '价格' },
      { id: 'p12', name: 'shippingMethod', type: 'string', required: true, description: '物流方式' },
      { id: 'p209', name: 'shippingCost', type: 'number', required: false, description: '运费' },
      { id: 'p210', name: 'shippingTime', type: 'string', required: false, description: '发货时间' },
      { id: 'p211', name: 'inventory', type: 'number', required: false, description: '库存' },
      { id: 'p212', name: 'warehouse', type: 'string', required: false, description: '仓库' },
      { id: 'p213', name: 'handlingTime', type: 'number', required: false, description: '处理时间(天)' },
      { id: 'p214', name: 'returnPolicy', type: 'string', required: false, description: '退货政策' },
      { id: 'p215', name: 'taxCode', type: 'string', required: false, description: '税码' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '22',
    type: 'listing',
    name: 'Listing',
    properties: [
      { id: 'p13', name: 'name', type: 'string', required: true, description: 'Listing名称' },
      { id: 'p14', name: 'platform', type: 'string', required: true, description: '平台' },
      { id: 'p15', name: 'status', type: 'string', required: true, description: '状态' },
      { id: 'p216', name: 'listingId', type: 'string', required: false, description: 'Listing ID' },
      { id: 'p217', name: 'url', type: 'string', required: false, description: 'Listing链接' },
      { id: 'p218', name: 'views', type: 'number', required: false, description: '浏览量' },
      { id: 'p219', name: 'sales', type: 'number', required: false, description: '销量' },
      { id: 'p220', name: 'rating', type: 'number', required: false, description: '评分' },
      { id: 'p221', name: 'reviewCount', type: 'number', required: false, description: '评价数' },
      { id: 'p222', name: 'publishedAt', type: 'date', required: false, description: '上架时间' },
      { id: 'p223', name: 'lastSyncAt', type: 'date', required: false, description: '最后同步时间' },
      { id: 'p224', name: 'isActive', type: 'boolean', required: false, description: '是否活跃' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockPropertyMappings: PropertyMapping[] = [
  {
    id: 'm1',
    sourceEntityId: '1',
    sourcePropertyId: 'p1',
    targetEntityId: '2',
    targetPropertyId: 'p4',
    transformation: '',
    createdAt: new Date(),
  },
  {
    id: 'm2',
    sourceEntityId: '2',
    sourcePropertyId: 'p6',
    targetEntityId: '21',
    targetPropertyId: 'p10',
    transformation: '',
    createdAt: new Date(),
  },
  {
    id: 'm3',
    sourceEntityId: '21',
    sourcePropertyId: 'p11',
    targetEntityId: '22',
    targetPropertyId: 'p13',
    transformation: '{{platform}} + {{productItem.name}}',
    createdAt: new Date(),
  },
];

export const mockPlatformRules: PlatformRule[] = [
  {
    id: 'r1',
    platform: 'Amazon',
    entityType: 'listing',
    propertyId: 'p6',
    rule: '标题长度不能超过200字符',
    validation: { maxLength: 200 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r2',
    platform: 'Walmart',
    entityType: 'listing',
    propertyId: 'p6',
    rule: '标题长度不能超过250字符',
    validation: { maxLength: 250 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r3',
    platform: 'eBay',
    entityType: 'listing',
    propertyId: 'p6',
    rule: '标题长度不能超过80字符',
    validation: { maxLength: 80 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r4',
    platform: 'Target',
    entityType: 'listing',
    propertyId: 'p6',
    rule: '标题长度不能超过150字符',
    validation: { maxLength: 150 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r5',
    platform: 'TikTok',
    entityType: 'listing',
    propertyId: 'p6',
    rule: '标题长度不能超过120字符',
    validation: { maxLength: 120 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r6',
    platform: 'Best Buy',
    entityType: 'listing',
    propertyId: 'p6',
    rule: '标题长度不能超过160字符',
    validation: { maxLength: 160 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r7',
    platform: 'Allegro',
    entityType: 'listing',
    propertyId: 'p6',
    rule: '标题长度不能超过50字符',
    validation: { maxLength: 50 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r8',
    platform: 'Shopify',
    entityType: 'listing',
    propertyId: 'p6',
    rule: '标题长度不能超过320字符',
    validation: { maxLength: 320 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r9',
    platform: 'Mercado Libre',
    entityType: 'listing',
    propertyId: 'p6',
    rule: '标题长度不能超过60字符',
    validation: { maxLength: 60 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
