version: '3.8'

services:
  schema:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schema-management
    ports:
      - "30:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
